import {
  House,
  ClipboardList,
  Users,
  GraduationCap,
  Settings,
  FileText,
} from "lucide-react";

export const menuItems = [
  {
    label: "dashboard",
    href: "/dashboard",
    Icon: House,
  },
  {
    label: "manajemen pegawai",
    href: "/manajemen-pegawai",
    Icon: Users,
  },
  {
    label: "manajemen pelatihan",
    href: "/manajemen-pelatihan",
    Icon: ClipboardList,
  },
  // {
  //   label: "rekomendasi pelatihan",
  //   href: "/rekomendasi-pelatihan",
  //   Icon: GraduationCap,
  // },
  {
    label: "laporan & rekapitulasi",
    href: "/laporan-rekapitulasi",
    Icon: FileText,
  },
  {
    label: "pengaturan & hak akses",
    href: "/pengaturan",
    Icon: Settings,
  },
];

export const employees = [
  {
    id: 1,
    nama: "Andi Saputra",
    nip: "1987654321",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Audit Keuangan",
    pelatihanTerakhir: "Pelatihan Audit Investigatif",
    status: "Aktif",
  },
  {
    id: 2,
    nama: "Budi Santoso",
    nip: "1987543210",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Manajemen Risiko",
    pelatihanTerakhir: "Pelatihan Manajemen Risiko",
    status: "Aktif",
  },
  {
    id: 3,
    nama: "Citra Dewi",
    nip: "1987432109",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Analisis Data",
    pelatihanTerakhir: "Pelatihan Data Governance",
    status: "Aktif",
  },
  {
    id: 4,
    nama: "Dedi Kurniawan",
    nip: "1987321098",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Forensik Keuangan",
    pelatihanTerakhir: "Pelatihan Forensik Keuangan",
    status: "Nonaktif",
  },
  {
    id: 5,
    nama: "Eka Putri",
    nip: "1987210987",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Kepemimpinan",
    pelatihanTerakhir: "Pelatihan Kepemimpinan ASN",
    status: "Aktif",
  },
  {
    id: 6,
    nama: "Fahmi Hidayat",
    nip: "1987109876",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Manajemen Proyek",
    pelatihanTerakhir: "Pelatihan Manajemen Proyek",
    status: "Aktif",
  },
  {
    id: 7,
    nama: "Gita Rahayu",
    nip: "1986998765",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Audit Teknologi Informasi",
    pelatihanTerakhir: "Pelatihan IT Audit",
    status: "Aktif",
  },
  {
    id: 8,
    nama: "Hadi Prasetyo",
    nip: "1986887654",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Hukum Administrasi Negara",
    pelatihanTerakhir: "Pelatihan Hukum Administrasi",
    status: "Nonaktif",
  },
  {
    id: 9,
    nama: "Indah Lestari",
    nip: "1986776543",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Pengadaan Barang dan Jasa",
    pelatihanTerakhir: "Pelatihan PBJ Pemerintah",
    status: "Aktif",
  },
  {
    id: 10,
    nama: "Joko Susilo",
    nip: "1986665432",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Investigasi Keuangan",
    pelatihanTerakhir: "Pelatihan Investigasi Keuangan",
    status: "Aktif",
  },
  {
    id: 11,
    nama: "Kurniawan Saputra",
    nip: "1986554321",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Kepemimpinan",
    pelatihanTerakhir: "Pelatihan Kepemimpinan Tingkat Lanjut",
    status: "Aktif",
  },
  {
    id: 12,
    nama: "Lina Permata",
    nip: "1986443210",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Manajemen Risiko",
    pelatihanTerakhir: "Pelatihan Manajemen Risiko",
    status: "Aktif",
  },
  {
    id: 13,
    nama: "Muhammad Rizky",
    nip: "1986332109",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Audit Investigatif",
    pelatihanTerakhir: "Pelatihan Audit Investigatif",
    status: "Aktif",
  },
  {
    id: 14,
    nama: "Nina Kurniasari",
    nip: "1986221098",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Akuntansi Pemerintahan",
    pelatihanTerakhir: "Pelatihan Akuntansi Pemerintah",
    status: "Nonaktif",
  },
  {
    id: 15,
    nama: "Oscar Ramadhan",
    nip: "1986110987",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Forensik Digital",
    pelatihanTerakhir: "Pelatihan Forensik Digital",
    status: "Aktif",
  },
  {
    id: 16,
    nama: "Putri Wulandari",
    nip: "1986009876",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Kepatuhan Internal",
    pelatihanTerakhir: "Pelatihan Kepatuhan Internal",
    status: "Aktif",
  },
  {
    id: 17,
    nama: "Qori Maulana",
    nip: "1985998765",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Analisis Data Keuangan",
    pelatihanTerakhir: "Pelatihan Analisis Data Keuangan",
    status: "Aktif",
  },
  {
    id: 18,
    nama: "Rina Setiawati",
    nip: "1985887654",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Penyusunan Anggaran",
    pelatihanTerakhir: "Pelatihan Penyusunan Anggaran",
    status: "Nonaktif",
  },
  {
    id: 19,
    nama: "Satria Wibowo",
    nip: "1985776543",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Manajemen Aset",
    pelatihanTerakhir: "Pelatihan Manajemen Aset Negara",
    status: "Aktif",
  },
  {
    id: 20,
    nama: "Tina Marlina",
    nip: "1985665432",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Perpajakan",
    pelatihanTerakhir: "Pelatihan Pajak Pemerintah",
    status: "Aktif",
  },
];

export const dataPelatihan = [
  {
    id: 1,
    nama: "Pelatihan Audit Internal",
    kategori: "Teknis",
    tanggal: "2025-04-10",
    durasi: "3 Hari",
    lokasi: "Jakarta",
    status: "Selesai",
    peserta: 25,
  },
  {
    id: 2,
    nama: "Manajemen Risiko",
    kategori: "Manajerial",
    tanggal: "2025-05-05",
    durasi: "2 Hari",
    lokasi: "Bandung",
    status: "Sedang Berlangsung",
    peserta: 18,
  },
  {
    id: 3,
    nama: "Teknik Investigasi Keuangan",
    kategori: "Teknis",
    tanggal: "2025-06-15",
    durasi: "5 Hari",
    lokasi: "Surabaya",
    status: "Akan Datang",
    peserta: 30,
  },
  {
    id: 4,
    nama: "Analisis Data untuk Audit",
    kategori: "Teknis",
    tanggal: "2025-07-20",
    durasi: "4 Hari",
    lokasi: "Yogyakarta",
    status: "Akan Datang",
    peserta: 22,
  },
  {
    id: 5,
    nama: "Pencegahan Fraud di Instansi Pemerintah",
    kategori: "Manajerial",
    tanggal: "2025-08-12",
    durasi: "3 Hari",
    lokasi: "Jakarta",
    status: "Akan Datang",
    peserta: 28,
  },
  {
    id: 6,
    nama: "Kepemimpinan dalam Organisasi",
    kategori: "Kepemimpinan",
    tanggal: "2025-09-10",
    durasi: "3 Hari",
    lokasi: "Medan",
    status: "Sedang Berlangsung",
    peserta: 20,
  },
  {
    id: 7,
    nama: "Manajemen Proyek untuk Pegawai",
    kategori: "Manajerial",
    tanggal: "2025-10-05",
    durasi: "4 Hari",
    lokasi: "Makassar",
    status: "Akan Datang",
    peserta: 15,
  },
  {
    id: 8,
    nama: "Pelatihan Pengolahan Data dengan Excel",
    kategori: "Teknis",
    tanggal: "2025-11-12",
    durasi: "2 Hari",
    lokasi: "Bandung",
    status: "Selesai",
    peserta: 35,
  },
  {
    id: 9,
    nama: "Strategi Negosiasi Efektif",
    kategori: "Kepemimpinan",
    tanggal: "2025-12-15",
    durasi: "3 Hari",
    lokasi: "Jakarta",
    status: "Akan Datang",
    peserta: 27,
  },
  {
    id: 10,
    nama: "Pengelolaan Konflik dalam Tim",
    kategori: "Kepemimpinan",
    tanggal: "2026-01-20",
    durasi: "3 Hari",
    lokasi: "Yogyakarta",
    status: "Akan Datang",
    peserta: 23,
  },
  {
    id: 11,
    nama: "Pemanfaatan AI untuk Efisiensi Kerja",
    kategori: "Teknis",
    tanggal: "2026-02-14",
    durasi: "5 Hari",
    lokasi: "Surabaya",
    status: "Sedang Berlangsung",
    peserta: 19,
  },
  {
    id: 12,
    nama: "Manajemen Waktu dan Produktivitas",
    kategori: "Manajerial",
    tanggal: "2026-03-01",
    durasi: "2 Hari",
    lokasi: "Jakarta",
    status: "Selesai",
    peserta: 32,
  },
];
