import {
  House,
  ClipboardList,
  Users,
  GraduationCap,
  Settings,
  FileText,
} from "lucide-react";

export const menuItems = [
  {
    label: "dashboard",
    href: "/dashboard",
    Icon: House,
  },
  {
    label: "manajemen pegawai",
    href: "/manajemen-pegawai",
    Icon: Users,
  },
  {
    label: "manajemen pelatihan",
    href: "/manajemen-pelatihan",
    Icon: ClipboardList,
  },
  {
    label: "rekomendasi pelatihan",
    href: "/rekomendasi-pelatihan",
    Icon: GraduationCap,
  },
  {
    label: "laporan & rekapitulasi",
    href: "/laporan-rekapitulasi",
    Icon: FileText,
  },
  {
    label: "pengaturan & hak akses",
    href: "/pengaturan",
    Icon: Settings,
  },
];

export const employees = [
  {
    id: 1,
    nama: "Andi Saputra",
    nip: "1987654321",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Audit Keuangan",
    pelatihanTerakhir: "Pelatihan Audit Investigatif",
    status: "Aktif",
  },
  {
    id: 2,
    nama: "Budi Santoso",
    nip: "1987543210",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Manajemen Risiko",
    pelatihanTerakhir: "Pelatihan Manajemen Risiko",
    status: "Aktif",
  },
  {
    id: 3,
    nama: "Citra Dewi",
    nip: "1987432109",
    jabatan: "Analis",
    unitKerja: "Inspektorat Wilayah III",
    kompetensi: "Analisis Data",
    pelatihanTerakhir: "Pelatihan Data Governance",
    status: "Aktif",
  },
  {
    id: 4,
    nama: "Dedi Kurniawan",
    nip: "1987321098",
    jabatan: "Auditor",
    unitKerja: "Inspektorat Wilayah I",
    kompetensi: "Forensik Keuangan",
    pelatihanTerakhir: "Pelatihan Forensik Keuangan",
    status: "Nonaktif",
  },
  {
    id: 5,
    nama: "Eka Putri",
    nip: "1987210987",
    jabatan: "Pengawas",
    unitKerja: "Inspektorat Wilayah II",
    kompetensi: "Kepemimpinan",
    pelatihanTerakhir: "Pelatihan Kepemimpinan ASN",
    status: "Aktif",
  },
];

export const dataPelatihan = [
  {
    id: 1,
    nama: "Pelatihan Audit Internal",
    tanggal: "2025-04-10",
    durasi: "3 Hari",
    lokasi: "Jakarta",
    status: "Selesai",
    peserta: 25,
  },
  {
    id: 2,
    nama: "Manajemen Risiko",
    tanggal: "2025-05-05",
    durasi: "2 Hari",
    lokasi: "Bandung",
    status: "Sedang Berlangsung",
    peserta: 18,
  },
  {
    id: 3,
    nama: "Teknik Investigasi Keuangan",
    tanggal: "2025-06-15",
    durasi: "5 Hari",
    lokasi: "Surabaya",
    status: "Akan Datang",
    peserta: 30,
  },
  {
    id: 4,
    nama: "Analisis Data untuk Audit",
    tanggal: "2025-07-20",
    durasi: "4 Hari",
    lokasi: "Yogyakarta",
    status: "Akan Datang",
    peserta: 22,
  },
  {
    id: 5,
    nama: "Pencegahan Fraud di Instansi Pemerintah",
    tanggal: "2025-08-12",
    durasi: "3 Hari",
    lokasi: "Jakarta",
    status: "Akan Datang",
    peserta: 28,
  },
];
